import Head from "next/head";
import IngredientFragment from "../components/IngredientFragment";
import RecipeFragment from "../components/RecipeFragment";

export default function Home() {
  return (
    <>
      <Head>
        <title>Recipea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-colorBlack text-colorTextOnBlack w-screen min-h-screen">
        <div className="p-2 border-b border-colorWhite/50 ">
          <h1 className="font-semibold">🍐 RECIPEA</h1>
        </div>
        <div className="flex flex-col p-3 gap-4">
          <button className="w-1/2 mx-auto button bg-colorWhite hover:bg-colorGray text-colorBlack hover:text-colorWhite mt-2">
            Show Possible Recipes
          </button>
          <IngredientFragment />
          <RecipeFragment />
        </div>
      </main>
    </>
  );
}
